In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("customer_segmentation.csv")
df

country client_type  average_basket  average_price  visit_number   age  \
0         it  occasional             2.0          756.0           2.0  46.0   
1         uk  occasional             3.0         6229.0           1.0  66.0   
2         fr  occasional             1.0         1803.0           2.0  64.0   
3         fr  occasional             1.0         1857.0           3.0  52.0   
4         fr  occasional             1.0         1761.0           2.0  58.0   
...      ...         ...             ...            ...           ...   ...   
8995      uk  occasional             2.0         6346.0           1.0  67.0   
8996      it  occasional             2.0         1316.0           3.0  45.0   
8997      fr  occasional             1.0         1956.0           3.0  43.0   
8998      fr  occasional             1.0         1381.0           3.0  60.0   
8999      fr  occasional             1.0         2167.0           2.0  61.0   

      gender  hobbies  customer_id  
0     female      NaN            0  
1       male      NaN            1  
2       male      NaN            2  
3       male      NaN            3  
4       male      NaN            4  
...      ...      ...          ...  
8995    male      NaN         8995  
8996    male      NaN         8996  
8997  female      NaN         8997  
8998    male  reading         8998  
8999    male      NaN         8999  

[9000 rows x 9 columns]

In [3]:
df = df.drop("customer_id", axis=1)
df

country client_type  average_basket  average_price  visit_number   age  \
0         it  occasional             2.0          756.0           2.0  46.0   
1         uk  occasional             3.0         6229.0           1.0  66.0   
2         fr  occasional             1.0         1803.0           2.0  64.0   
3         fr  occasional             1.0         1857.0           3.0  52.0   
4         fr  occasional             1.0         1761.0           2.0  58.0   
...      ...         ...             ...            ...           ...   ...   
8995      uk  occasional             2.0         6346.0           1.0  67.0   
8996      it  occasional             2.0         1316.0           3.0  45.0   
8997      fr  occasional             1.0         1956.0           3.0  43.0   
8998      fr  occasional             1.0         1381.0           3.0  60.0   
8999      fr  occasional             1.0         2167.0           2.0  61.0   

      gender  hobbies  
0     female      NaN  
1       male      NaN  
2       male      NaN  
3       male      NaN  
4       male      NaN  
...      ...      ...  
8995    male      NaN  
8996    male      NaN  
8997  female      NaN  
8998    male  reading  
8999    male      NaN  

[9000 rows x 8 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9000 entries, 0 to 8999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   country         9000 non-null   object 
 1   client_type     9000 non-null   object 
 2   average_basket  9000 non-null   float64
 3   average_price   8536 non-null   float64
 4   visit_number    9000 non-null   float64
 5   age             8820 non-null   float64
 6   gender          8901 non-null   object 
 7   hobbies         887 non-null    object 
dtypes: float64(4), object(4)
memory usage: 562.6+ KB


In [5]:
df.describe(include = 'all')

country client_type  average_basket  average_price  visit_number  \
count     9000        9000     9000.000000    8536.000000   9000.000000   
unique       3           3             NaN            NaN           NaN   
top         fr  occasional             NaN            NaN           NaN   
freq      5418        6206             NaN            NaN           NaN   
mean       NaN         NaN        2.268667    4869.591495      4.811222   
std        NaN         NaN        1.557947    4098.673605      5.101245   
min        NaN         NaN        1.000000      -1.000000      1.000000   
25%        NaN         NaN        1.000000    1807.000000      2.000000   
50%        NaN         NaN        2.000000    2926.000000      3.000000   
75%        NaN         NaN        3.000000    6997.250000      7.000000   
max        NaN         NaN       12.000000   28137.000000     33.000000   

                age gender hobbies  
count   8820.000000   8901     887  
unique          NaN      2       4  
top             NaN   male  movies  
freq            NaN   6232     275  
mean      55.069501    NaN     NaN  
std       10.186070    NaN     NaN  
min       18.000000    NaN     NaN  
25%       48.000000    NaN     NaN  
50%       55.000000    NaN     NaN  
75%       62.000000    NaN     NaN  
max       87.000000    NaN     NaN

In [7]:
mask_average_price_positive_or_null = (df.average_price > 0) | (df.average_price.isnull())
df = df[mask_average_price_positive_or_null]
df

country client_type  average_basket  average_price  visit_number   age  \
0         it  occasional             2.0          756.0           2.0  46.0   
1         uk  occasional             3.0         6229.0           1.0  66.0   
2         fr  occasional             1.0         1803.0           2.0  64.0   
3         fr  occasional             1.0         1857.0           3.0  52.0   
4         fr  occasional             1.0         1761.0           2.0  58.0   
...      ...         ...             ...            ...           ...   ...   
8995      uk  occasional             2.0         6346.0           1.0  67.0   
8996      it  occasional             2.0         1316.0           3.0  45.0   
8997      fr  occasional             1.0         1956.0           3.0  43.0   
8998      fr  occasional             1.0         1381.0           3.0  60.0   
8999      fr  occasional             1.0         2167.0           2.0  61.0   

      gender  hobbies  
0     female      NaN  
1       male      NaN  
2       male      NaN  
3       male      NaN  
4       male      NaN  
...      ...      ...  
8995    male      NaN  
8996    male      NaN  
8997  female      NaN  
8998    male  reading  
8999    male      NaN  

[8769 rows x 8 columns]

In [8]:
df.describe(include = 'all')
df

country client_type  average_basket  average_price  visit_number   age  \
0         it  occasional             2.0          756.0           2.0  46.0   
1         uk  occasional             3.0         6229.0           1.0  66.0   
2         fr  occasional             1.0         1803.0           2.0  64.0   
3         fr  occasional             1.0         1857.0           3.0  52.0   
4         fr  occasional             1.0         1761.0           2.0  58.0   
...      ...         ...             ...            ...           ...   ...   
8995      uk  occasional             2.0         6346.0           1.0  67.0   
8996      it  occasional             2.0         1316.0           3.0  45.0   
8997      fr  occasional             1.0         1956.0           3.0  43.0   
8998      fr  occasional             1.0         1381.0           3.0  60.0   
8999      fr  occasional             1.0         2167.0           2.0  61.0   

      gender  hobbies  
0     female      NaN  
1       male      NaN  
2       male      NaN  
3       male      NaN  
4       male      NaN  
...      ...      ...  
8995    male      NaN  
8996    male      NaN  
8997  female      NaN  
8998    male  reading  
8999    male      NaN  

[8769 rows x 8 columns]

In [9]:
df.isnull().sum() / df.shape[0]


country           0.000000
client_type       0.000000
average_basket    0.000000
average_price     0.052914
visit_number      0.000000
age               0.020071
gender            0.011062
hobbies           0.902155
dtype: float64

In [12]:
df = df.drop('hobbies', axis=1)
df

country client_type  average_basket  average_price  visit_number   age  \
0         it  occasional             2.0          756.0           2.0  46.0   
1         uk  occasional             3.0         6229.0           1.0  66.0   
2         fr  occasional             1.0         1803.0           2.0  64.0   
3         fr  occasional             1.0         1857.0           3.0  52.0   
4         fr  occasional             1.0         1761.0           2.0  58.0   
...      ...         ...             ...            ...           ...   ...   
8995      uk  occasional             2.0         6346.0           1.0  67.0   
8996      it  occasional             2.0         1316.0           3.0  45.0   
8997      fr  occasional             1.0         1956.0           3.0  43.0   
8998      fr  occasional             1.0         1381.0           3.0  60.0   
8999      fr  occasional             1.0         2167.0           2.0  61.0   

      gender  
0     female  
1       male  
2       male  
3       male  
4       male  
...      ...  
8995    male  
8996    male  
8997  female  
8998    male  
8999    male  

[8769 rows x 7 columns]

In [13]:
gender_mode = df["gender"].mode()[0]
df.loc[:, "gender"] = df["gender"].fillna(gender_mode)

In [14]:
means = df[["average_price", "age"]].mean()
df.loc[:, ["average_price", "age"]] = df[["average_price", "age"]].fillna(means)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8769 entries, 0 to 8999
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   country         8769 non-null   object 
 1   client_type     8769 non-null   object 
 2   average_basket  8769 non-null   float64
 3   average_price   8769 non-null   float64
 4   visit_number    8769 non-null   float64
 5   age             8769 non-null   float64
 6   gender          8769 non-null   object 
dtypes: float64(4), object(3)
memory usage: 548.1+ KB


In [16]:
y = df["client_type"]
X = df.drop("client_type", axis=1)

In [17]:
y

0       occasional
1       occasional
2       occasional
3       occasional
4       occasional
           ...    
8995    occasional
8996    occasional
8997    occasional
8998    occasional
8999    occasional
Name: client_type, Length: 8769, dtype: object

In [18]:
from sklearn.preprocessing import LabelEncoder

labelencoder = LabelEncoder()
y = labelencoder.fit_transform(y)

print(y)
print(labelencoder.classes_)

[1 1 1 ... 1 1 1]
['frequent' 'occasional' 'vip']


In [19]:
from sklearn.preprocessing import OneHotEncoder

onehotencoder = OneHotEncoder(sparse=False)
X_dummy = onehotencoder.fit_transform(X[["country", "gender"]])

print(X_dummy)
print(onehotencoder.categories_)

[[0. 1. 0. 1. 0.]
 [0. 0. 1. 0. 1.]
 [1. 0. 0. 0. 1.]
 ...
 [1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]]
[array(['fr', 'it', 'uk'], dtype=object), array(['female', 'male'], dtype=object)]


C:\Users\Hendriks\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [20]:
import numpy as np
dummy_cols = np.concatenate((onehotencoder.categories_[0], onehotencoder.categories_[1]), axis=None)
print(dummy_cols)

['fr' 'it' 'uk' 'female' 'male']


In [21]:
onehotencoder.get_feature_names_out()

array(['country_fr', 'country_it', 'country_uk', 'gender_female',
       'gender_male'], dtype=object)

In [22]:
X_dummy = pd.DataFrame(X_dummy, columns=onehotencoder.get_feature_names_out())
X_dummy

country_fr  country_it  country_uk  gender_female  gender_male
0            0.0         1.0         0.0            1.0          0.0
1            0.0         0.0         1.0            0.0          1.0
2            1.0         0.0         0.0            0.0          1.0
3            1.0         0.0         0.0            0.0          1.0
4            1.0         0.0         0.0            0.0          1.0
...          ...         ...         ...            ...          ...
8764         0.0         0.0         1.0            0.0          1.0
8765         0.0         1.0         0.0            0.0          1.0
8766         1.0         0.0         0.0            1.0          0.0
8767         1.0         0.0         0.0            0.0          1.0
8768         1.0         0.0         0.0            0.0          1.0

[8769 rows x 5 columns]

In [23]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_num = scaler.fit_transform(X[["average_basket", "average_price", "visit_number", "age"]])

In [24]:
X_num

array([[-0.17024904, -1.07207574, -0.55228343, -0.90226009],
       [ 0.47269404,  0.30880939, -0.74818866,  1.08556673],
       [-0.81319212, -0.80790861, -0.55228343,  0.88678405],
       ...,
       [-0.81319212, -0.76930539, -0.35637819, -1.20043411],
       [-0.81319212, -0.91438285, -0.35637819,  0.48921869],
       [-0.81319212, -0.71606826, -0.55228343,  0.58861003]])

In [25]:
X_num = pd.DataFrame(X_num, columns=["average_basket", "average_price", "visit_number", "age"])

In [26]:
X_num

average_basket  average_price  visit_number       age
0          -0.170249      -1.072076     -0.552283 -0.902260
1           0.472694       0.308809     -0.748189  1.085567
2          -0.813192      -0.807909     -0.552283  0.886784
3          -0.813192      -0.794284     -0.356378 -0.305912
4          -0.813192      -0.818506     -0.552283  0.290436
...              ...            ...           ...       ...
8764       -0.170249       0.338329     -0.748189  1.184958
8765       -0.170249      -0.930783     -0.356378 -1.001651
8766       -0.813192      -0.769305     -0.356378 -1.200434
8767       -0.813192      -0.914383     -0.356378  0.489219
8768       -0.813192      -0.716068     -0.552283  0.588610

[8769 rows x 4 columns]

In [27]:
X = pd.concat([X_dummy, X_num], axis=1)

In [28]:
X

country_fr  country_it  country_uk  gender_female  gender_male  \
0            0.0         1.0         0.0            1.0          0.0   
1            0.0         0.0         1.0            0.0          1.0   
2            1.0         0.0         0.0            0.0          1.0   
3            1.0         0.0         0.0            0.0          1.0   
4            1.0         0.0         0.0            0.0          1.0   
...          ...         ...         ...            ...          ...   
8764         0.0         0.0         1.0            0.0          1.0   
8765         0.0         1.0         0.0            0.0          1.0   
8766         1.0         0.0         0.0            1.0          0.0   
8767         1.0         0.0         0.0            0.0          1.0   
8768         1.0         0.0         0.0            0.0          1.0   

      average_basket  average_price  visit_number       age  
0          -0.170249      -1.072076     -0.552283 -0.902260  
1           0.472694       0.308809     -0.748189  1.085567  
2          -0.813192      -0.807909     -0.552283  0.886784  
3          -0.813192      -0.794284     -0.356378 -0.305912  
4          -0.813192      -0.818506     -0.552283  0.290436  
...              ...            ...           ...       ...  
8764       -0.170249       0.338329     -0.748189  1.184958  
8765       -0.170249      -0.930783     -0.356378 -1.001651  
8766       -0.813192      -0.769305     -0.356378 -1.200434  
8767       -0.813192      -0.914383     -0.356378  0.489219  
8768       -0.813192      -0.716068     -0.552283  0.588610  

[8769 rows x 9 columns]

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7)

In [31]:
from sklearn.tree import DecisionTreeClassifier

In [32]:
my_tree_classifier = DecisionTreeClassifier()

In [33]:
my_tree_classifier.fit(X_train, y_train)

DecisionTreeClassifier()

https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html

In [34]:
my_tree_classifier.score(X_train, y_train)

0.9998370804822417

In [35]:
my_tree_classifier.score(X_test, y_test)

0.9828962371721779

In [36]:
df_new = pd.read_csv("customer_segmentation_new.csv")
df_new

country  average_basket  average_price  visit_number   age  gender  \
0        fr             2.0         6864.0          19.0  60.0    male   
1        uk             5.0        10703.0          13.0  51.0  female   
2        fr             1.0         2298.0           1.0  62.0    male   
3        fr             3.0         2343.0           4.0  41.0  female   
4        fr             2.0         2383.0           2.0  49.0    male   
..      ...             ...            ...           ...   ...     ...   
995      fr             2.0         1590.0           3.0  42.0    male   
996      fr             2.0         7075.0          14.0  64.0  female   
997      uk             3.0            NaN           4.0  50.0  female   
998      fr             4.0         6408.0           7.0  47.0    male   
999      fr             2.0         1100.0           2.0  75.0    male   

     hobbies  customer_id  
0        NaN         9000  
1        NaN         9001  
2        NaN         9002  
3      sport         9003  
4        NaN         9004  
..       ...          ...  
995      NaN         9995  
996      NaN         9996  
997  reading         9997  
998      NaN         9998  
999      NaN         9999  

[1000 rows x 8 columns]

In [37]:
df_new.describe(include='all')

country  average_basket  average_price  visit_number         age  \
count     1000     1000.000000     950.000000   1000.000000  980.000000   
unique       3             NaN            NaN           NaN         NaN   
top         fr             NaN            NaN           NaN         NaN   
freq       582             NaN            NaN           NaN         NaN   
mean       NaN        2.329000    5065.538947      4.991000   54.619388   
std        NaN        1.614734    4137.659405      5.131203    9.815199   
min        NaN        1.000000      -1.000000      1.000000   25.000000   
25%        NaN        1.000000    1855.750000      2.000000   48.000000   
50%        NaN        2.000000    3504.500000      3.000000   55.000000   
75%        NaN        3.000000    7084.000000      8.000000   61.000000   
max        NaN       11.000000   27193.000000     32.000000   86.000000   

       gender hobbies  customer_id  
count     989     113  1000.000000  
unique      2       4          NaN  
top      male   sport          NaN  
freq      701      41          NaN  
mean      NaN     NaN  9499.500000  
std       NaN     NaN   288.819436  
min       NaN     NaN  9000.000000  
25%       NaN     NaN  9249.750000  
50%       NaN     NaN  9499.500000  
75%       NaN     NaN  9749.250000  
max       NaN     NaN  9999.000000

In [38]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   country         1000 non-null   object 
 1   average_basket  1000 non-null   float64
 2   average_price   950 non-null    float64
 3   visit_number    1000 non-null   float64
 4   age             980 non-null    float64
 5   gender          989 non-null    object 
 6   hobbies         113 non-null    object 
 7   customer_id     1000 non-null   int64  
dtypes: float64(4), int64(1), object(3)
memory usage: 62.6+ KB


In [39]:
df_new = pd.read_csv("customer_segmentation_new.csv")
df_new = df_new.drop("customer_id", axis=1)
mask_average_price_positive_or_null = (df_new.average_price > 0) | (df_new.average_price.isnull())
df_new = df_new[mask_average_price_positive_or_null]
df_new = df_new.drop("hobbies", axis=1)
df_new.loc[:, "gender"] = df_new["gender"].fillna(gender_mode)
df_new.loc[:, ["average_price", "age"]] = df_new[["average_price", "age"]].fillna(means)

X_new = df_new
# Encode categorical features + Scale numerical features 
X_new_dummy = pd.DataFrame(onehotencoder.transform(X_new[["country", "gender"]]), columns=onehotencoder.get_feature_names_out())
X_new_num = scaler.transform(X_new[["average_basket", "average_price", "visit_number", "age"]])
X_new_num = pd.DataFrame(X_new_num, columns=["average_basket", "average_price", "visit_number", "age"])
X_new = pd.concat([X_new_dummy, X_new_num], axis=1)

# Predict
y_predict = my_tree_classifier.predict(X_new)

In [40]:
y_predict

array([0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       2, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 2, 1, 1,
       1, 1, 2, 1, 0, 1, 2, 1, 1, 0, 1, 2, 0, 1, 1, 1, 0, 1, 1, 0, 2, 1,
       1, 1, 1, 1, 1, 0, 1, 2, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 2, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 2, 1, 1, 1, 2, 1, 0, 2, 0, 0, 1, 1,
       2, 0, 1, 1, 1, 1, 0, 2, 1, 2, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 2, 1, 1, 1, 1, 1, 0, 1, 2, 2, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 2, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 2, 1,
       1, 2, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,

In [41]:
pd.DataFrame(labelencoder.classes_, columns=['Class'])

Class
0    frequent
1  occasional
2         vip

In [42]:
labelencoder.inverse_transform(y_predict)

array(['frequent', 'frequent', 'occasional', 'occasional', 'occasional',
       'frequent', 'frequent', 'frequent', 'frequent', 'occasional',
       'frequent', 'occasional', 'occasional', 'occasional', 'occasional',
       'occasional', 'occasional', 'occasional', 'occasional',
       'occasional', 'occasional', 'vip', 'occasional', 'occasional',
       'occasional', 'frequent', 'occasional', 'occasional', 'occasional',
       'occasional', 'occasional', 'frequent', 'occasional', 'occasional',
       'occasional', 'occasional', 'frequent', 'occasional', 'occasional',
       'frequent', 'occasional', 'occasional', 'occasional', 'occasional',
       'vip', 'frequent', 'occasional', 'frequent', 'occasional',
       'occasional', 'occasional', 'occasional', 'occasional',
       'occasional', 'occasional', 'occasional', 'occasional', 'frequent',
       'occasional', 'frequent', 'frequent', 'frequent', 'occasional',
       'frequent', 'occasional', 'frequent', 'frequent', 'occasional',
    

In [43]:
my_tree_classifier.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'random_state': None,
 'splitter': 'best'}

In [44]:
from sklearn.model_selection import GridSearchCV

In [45]:
params = {
    'min_samples_split': [0.001, 0.01, 0.1, 0.2, 0.5],
    # 'min_samples_split': np.arange(0.0001, 0.002, 0.0001),
    "max_depth": [2,5,10,None]
}
my_grid_tree_classifier = GridSearchCV(DecisionTreeClassifier(), params, cv=3, verbose=3)

In [46]:
my_grid_tree_classifier.fit(X_train, y_train)

Fitting 3 folds for each of 20 candidates, totalling 60 fits
[CV 1/3] END max_depth=2, min_samples_split=0.001;, score=0.927 total time=   0.0s
[CV 2/3] END max_depth=2, min_samples_split=0.001;, score=0.918 total time=   0.0s
[CV 3/3] END max_depth=2, min_samples_split=0.001;, score=0.934 total time=   0.0s
[CV 1/3] END max_depth=2, min_samples_split=0.01;, score=0.927 total time=   0.0s
[CV 2/3] END max_depth=2, min_samples_split=0.01;, score=0.918 total time=   0.0s
[CV 3/3] END max_depth=2, min_samples_split=0.01;, score=0.934 total time=   0.0s
[CV 1/3] END max_depth=2, min_samples_split=0.1;, score=0.927 total time=   0.0s
[CV 2/3] END max_depth=2, min_samples_split=0.1;, score=0.918 total time=   0.0s
[CV 3/3] END max_depth=2, min_samples_split=0.1;, score=0.934 total time=   0.0s
[CV 1/3] END max_depth=2, min_samples_split=0.2;, score=0.927 total time=   0.0s
[CV 2/3] END max_depth=2, min_samples_split=0.2;, score=0.918 total time=   0.0s
[CV 3/3] END max_depth=2, min_samples_s

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [2, 5, 10, None],
                         'min_samples_split': [0.001, 0.01, 0.1, 0.2, 0.5]},
             verbose=3)

In [47]:
my_grid_tree_classifier.best_params_

{'max_depth': 10, 'min_samples_split': 0.001}

In [48]:
my_grid_tree_classifier.score(X_train, y_train)

0.9947865754317368

In [49]:
my_grid_tree_classifier.score(X_test, y_test)

0.9847966552641582

In [50]:
my_grid_tree_classifier.predict_proba(X_test)

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       ...,
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.]])